#!/usr/bin/python3

def input_chain(message):
    chain = []
    sink = ""
    while sink != "break":
        sink = input(message) 
        if sink != "break":
            chain.append(sink)
    return chain

x_name = input("Int Name: ")
f_name = x_name.replace(" ", "_")
e_chain = input_chain("(+)Equipment: ")
i_chain = input_chain("(+)Element: ")
s_chain = input_chain("(+)Step: ")

export_string = ""
export_string += "&N\n" + f_name + "\n"
export_string += "&E\n" + "\n".join(e_chain) + "\n"
export_string += "&N\n" + "\n".join(i_chain) + "\n"
export_string += "&N\n" + "\n".join(s_chain) + "\n"

with open("int/" + f_name + ".int", "w") as int_out:
    int_out.write(export_string)
